const subjects = [
  { slot: 'E1', code: 'AE317', name: 'POWER UNITS AND TRANSMISSION' },
  { slot: 'E1', code: 'AE411', name: 'VEHICLE MAINTENANCE & TRIBOLOGY' },
  {
    slot: 'E1',
    code: 'CE201',
    name: 'CIVIL ENGINEERING BASICS AND APPLICATIONS',
  },
  { slot: 'E1', code: 'CE205', name: 'FLUID MECHANICS' },
  {
    slot: 'E1',
    code: 'CE301',
    name: 'ANALYSIS OF DETERMINATE STRUCTURES',
  },
  { slot: 'E1', code: 'CH405', name: 'Fiber Technology' },
  { slot: 'E1', code: 'CO201', name: 'DATA STRUCTURES' },
  { slot: 'E1', code: 'CO305', name: 'INFORMATION THEORY AND CODING' },
  { slot: 'E1', code: 'CO313', name: 'COMPUTER GRAPHICS' },
  { slot: 'E1', code: 'CO325', name: 'Probability Statistics' },
  { slot: 'E1', code: 'CO327', name: 'MACHINE LEARNING' },
  { slot: 'E1', code: 'CO415', name: 'WIRELESS AND MOBILE COMPUTING' },
  { slot: 'E1', code: 'CO423', name: 'SWARM & EVOLUTIONARY COMPUTING' },
  { slot: 'E1', code: 'CO425', name: 'Web Technology' },
  { slot: 'E1', code: 'CO427', name: 'WEB TECHNOLOGY' },
  { slot: 'E1', code: 'CO433', name: 'Distributed Systems' },
  { slot: 'E1', code: 'EC307', name: 'ANTENNA DESIGN' },
  { slot: 'E1', code: 'EC319', name: 'CMOS ANALOG INTEGRATED CIRCUIT' },
  { slot: 'E1', code: 'EC407', name: 'Optical Communication' },
  { slot: 'E1', code: 'EC409', name: 'Computer Vision' },
  { slot: 'E1', code: 'EE317', name: 'RENEWABLE ENERGY SYSTEMS' },
  { slot: 'E1', code: 'EE319', name: 'DIGITAL SYSTEM DESIGN' },
  {
    slot: 'E1',
    code: 'EE353a',
    name: 'Electrical Machines and Power System',
  },
  {
    slot: 'E1',
    code: 'EN205',
    name: 'ENVIRONMENTAL CHEMISTRY & MICROBIOLOGY',
  },
  {
    slot: 'E1',
    code: 'EP309',
    name: 'QUANTUM INFORMATION AND COMPUTING',
  },
  { slot: 'E1', code: 'HU305', name: 'Macroeconomics' },
  { slot: 'E1', code: 'HU313', name: 'Creative Writing Skills' },
  { slot: 'E1', code: 'HU353a', name: 'International Trade' },
  { slot: 'E1', code: 'HU409', name: 'Soft Skills Development' },
  { slot: 'E1', code: 'IT323', name: 'MACHINE LEARNING' },
  { slot: 'E1', code: 'IT425', name: 'NATURAL LANGUAGE PROCESSING' },
  { slot: 'E1', code: 'IT431', name: 'INFORMATION SECURITY AND AUDIT' },
  { slot: 'E1', code: 'MC307', name: 'OBJECT ORIENTED PROGRAMMING' },
  { slot: 'E1', code: 'ME201', name: 'MECHANICS OF SOLIDS' },
  { slot: 'E1', code: 'ME351a', name: 'POWER PLANT ENGINEERING' },
  { slot: 'E1', code: 'ME419', name: 'ROBOTICS & AUTOMATION' },
  { slot: 'E1', code: 'PE301', name: 'CASTING TECHNOLOGY' },
  { slot: 'E1', code: 'PE405', name: 'METAL FORMING & PRESS WORKING' },
  { slot: 'E1', code: 'SE313', name: 'Advanced Data Structures' },
  {
    slot: 'E10',
    code: 'AE409',
    name: 'COMPUTER AIDED VEHICLE DESIGN AND SAFETY',
  },
  {
    slot: 'E10',
    code: 'BT407',
    name: 'BIOPROCESS TECH & DOWNSTREAM PROCESS',
  },
  { slot: 'E10', code: 'CE413', name: 'WATER RESOURCES MANAGEMENT' },
  { slot: 'E10', code: 'CE427', name: 'Wind Loads on Structures' },
  {
    slot: 'E10',
    code: 'ME407',
    name: 'REFRIGERATION & AIR CONDITIONING',
  },
  { slot: 'E10', code: 'ME415', name: 'PROJECT MANAGEMENT' },
  { slot: 'E10', code: 'SE425', name: 'Intellectual Property Rights' },
  { slot: 'E2', code: 'AE309', name: 'OPERATIONS RESEARCH' },
  { slot: 'E2', code: 'AE413', name: 'VEHICLE TRANSPORT MANAGEMENT' },
  { slot: 'E2', code: 'BT301', name: 'IMMUNOLOGY AND IMMUNO-TECHNOLOGY' },
  {
    slot: 'E2',
    code: 'BT421',
    name: 'Pharmacogenomics and Personalized Medicine',
  },
  { slot: 'E2', code: 'CE207', name: 'ENGINEERING ANALYSIS AND DESIGN' },
  { slot: 'E2', code: 'CE303', name: 'DESIGN OF RCC STRUCTURES' },
  {
    slot: 'E2',
    code: 'CH201',
    name: 'Chemical Engineering Process Calculations',
  },
  { slot: 'E2', code: 'CH407', name: 'Polymer Blends and Composites' },
  { slot: 'E2', code: 'CO325', name: 'Probability Statistics' },
  { slot: 'E2', code: 'CO423', name: 'SWARM & EVOLUTIONARY COMPUTING' },
  { slot: 'E2', code: 'CO425', name: 'Web Technology' },
  { slot: 'E2', code: 'CO427', name: 'WEB TECHNOLOGY' },
  { slot: 'E2', code: 'CO431', name: 'Reinforcement Learning' },
  { slot: 'E2', code: 'EC425', name: 'Mixed Signal Design' },
  { slot: 'E2', code: 'EC429', name: 'Emerging Semiconductor Devices' },
  {
    slot: 'E2',
    code: 'EC309',
    name: 'Bio Medical Electronics &amp; Instrumentation',
  },
  { slot: 'E2', code: 'EC323', name: 'CONTROL SYSTEMS' },
  { slot: 'E2', code: 'EE307', name: 'POWER STATION PRACTICES' },
  { slot: 'E2', code: 'EE313a', name: 'Engineering Analysis and Design' },
  {
    slot: 'E2',
    code: 'EE357a',
    name: 'UTILIZATION OF ELECTRICAL ENERGY',
  },
  { slot: 'E2', code: 'EN305', name: 'SOIL POLLUTION AND REMEDIATION' },
  {
    slot: 'E2',
    code: 'EN421',
    name: 'Design of Water Distribution Network.',
  },
  { slot: 'E2', code: 'EP305', name: 'ATOMIC AND MOLECULAR PHYSICS' },
  { slot: 'E2', code: 'EP415', name: 'NANO SCIENCE AND TECHNOLOGY' },
  { slot: 'E2', code: 'HU309', name: 'Indian Economy' },
  { slot: 'E2', code: 'IT201', name: 'DATA STRUCTURES' },
  { slot: 'E2', code: 'IT307', name: 'PATTERN RECOGNITION' },
  { slot: 'E2', code: 'IT407', name: 'INFORMATION AND NETWORK SECURITY' },
  { slot: 'E2', code: 'IT411', name: 'DIGITAL IMAGE PROCESSING' },
  { slot: 'E2', code: 'MC407', name: 'CRYPTOGRAPHY & NETWORK SECURITY' },
  { slot: 'E2', code: 'ME301', name: 'FLUID SYSTEMS' },
  { slot: 'E2', code: 'ME411', name: 'I.C. ENGINES' },
  { slot: 'E2', code: 'ME435', name: 'OPTIMIZATION TECHNIQUES' },
  { slot: 'E2', code: 'SE307', name: 'COMPUTER GRAPHICS' },
  { slot: 'E2', code: 'SE429', name: 'Data Warehouse & Data Mining' },
  { slot: 'E3', code: 'BT325', name: 'CELL BIOLOGY' },
  { slot: 'E3', code: 'CE309', name: 'ENVIRONMENTAL ENGINEERING DESIGN' },
  {
    slot: 'E3',
    code: 'CE321',
    name: 'DISASTER PREPAREDNESS AND MITIGATION',
  },
  { slot: 'E3', code: 'CH203', name: 'Transport Phenomena' },
  { slot: 'E3', code: 'CH323', name: 'Biomaterials' },
  { slot: 'E3', code: 'CO203', name: 'OBJECT ORIENTED PROGRAMMING' },
  { slot: 'E3', code: 'CO301', name: 'SOFTWARE ENGINEERING' },
  { slot: 'E3', code: 'CO303', name: 'THEORY OF COMPUTATION' },
  { slot: 'E3', code: 'CO313', name: 'COMPUTER GRAPHICS' },
  { slot: 'E3', code: 'CO327', name: 'MACHINE LEARNING' },
  { slot: 'E3', code: 'CO415', name: 'WIRELESS AND MOBILE COMPUTING' },
  { slot: 'E3', code: 'CO425', name: 'Web Technology' },
  { slot: 'E3', code: 'EC325', name: 'Probability and Random Process' },
  { slot: 'E3', code: 'EC431', name: 'MEMS and Sensor Design' },

  {
    slot: 'E3',
    code: 'EC445',
    name: 'Nanophotonics Devices for Communications',
  },
  { slot: 'E3', code: 'EC311', name: 'ALGORITHM ANALYSIS AND DESIGN' },
  { slot: 'E3', code: 'EE321', name: 'SOFT COMPUTING' },
  { slot: 'E3', code: 'EE407', name: 'INSTRUMENTATION AND MEASUREMENT' },
  {
    slot: 'E3',
    code: 'EE429',
    name: 'POWER ELECTRONICS APPLICATION TO PHOTO-VOLTAIC SYSTEMS',
  },
  { slot: 'E3', code: 'EN311', name: 'CLIMATE CHANGE & CDM' },
  { slot: 'E3', code: 'EP405', name: 'VLSI AND FPGA DESIGN' },
  { slot: 'E3', code: 'HU315', name: 'Non-Verbal Communication' },
  {
    slot: 'E3',
    code: 'HU351a',
    name: 'Mathematical Economics and Econometrics',
  },
  { slot: 'E3', code: 'IT201', name: 'DATA STRUCTURES' },
  { slot: 'E3', code: 'IT321', name: 'MALWARE ANALYSIS' },
  { slot: 'E3', code: 'IT325', name: 'SECURE CODING' },
  { slot: 'E3', code: 'IT411', name: 'DIGITAL IMAGE PROCESSING' },
  { slot: 'E3', code: 'MC315', name: 'MODERN ALGEBRA' },
  {
    slot: 'E3',
    code: 'MC409',
    name: 'MATHEMATICAL MODELING & SIMULATION',
  },
  { slot: 'E3', code: 'ME361', name: 'INDUSTRIAL ENGINEERING' },
  { slot: 'E3', code: 'ME411', name: 'I.C. ENGINES' },
  { slot: 'E3', code: 'PE307', name: 'FINITE ELEMENT METHOD' },
  { slot: 'E3', code: 'PE413', name: 'ROBOTICS AND AUTOMATION' },
  { slot: 'E3', code: 'SE305', name: 'Software Requirement Engineering' },
  { slot: 'E4', code: 'BT317', name: 'Enzymology and Enzyme Technology' },
  {
    slot: 'E4',
    code: 'BT405',
    name: 'FUNDAMENTAL OF COMPUTATIONAL BIOLOGY',
  },
  { slot: 'E4', code: 'CE305', name: 'MECHANICS OF MATERIALS' },
  {
    slot: 'E4',
    code: 'CE307',
    name: 'ADVANCED GEO-TECHNICAL ENGINEERING',
  },
  {
    slot: 'E4',
    code: 'CE325',
    name: 'HUMAN VALUES & ETHICS IN DISASTER MANAGEMENT',
  },
  { slot: 'E4', code: 'CH315', name: 'Plastic Technology' },
  { slot: 'E4', code: 'CH429', name: 'Energy Resources' },
  { slot: 'E4', code: 'CO205', name: 'DISCRETE STRUCTURES' },
  { slot: 'E4', code: 'CO325', name: 'Probability Statistics' },
  { slot: 'E4', code: 'C0411', name: 'Computer Vision' },
  { slot: 'E4', code: 'CO423', name: 'SWARM & EVOLUTIONARY COMPUTING' },
  { slot: 'E4', code: 'CO427', name: 'WEB TECHNOLOGY' },
  { slot: 'E4', code: 'EC313', name: 'Microprocessors and Interfacing' },
  { slot: 'E4', code: 'EC327', name: 'Time-Frequency Analysis' },
  { slot: 'E4', code: 'EC449', name: 'Adaptive Signal Processing' },
  { slot: 'E4', code: 'EC455', name: 'Data Analytics' },
  { slot: 'E4', code: 'EE305', name: 'SIGNALS AND SYSTEMS' },
  { slot: 'E4', code: 'EE323', name: 'FUNDAMENTALS OF MACHINE LEARNING' },
  { slot: 'E4', code: 'EE405', name: 'DIGITAL SIGNAL PROCESSING' },
  { slot: 'E4', code: 'EN409', name: 'INDUSTRIAL WASTE MANAGEMENT' },
  {
    slot: 'E4',
    code: 'EP419',
    name: 'INTRODUCTION TO AUTOMATION AND MOTION CONTROL',
  },
  { slot: 'E4', code: 'HU307', name: 'Basic Econometrics' },
  { slot: 'E4', code: 'HU413', name: 'Advanced Spoken Skills' },
  { slot: 'E4', code: 'IT303', name: 'COMPUTER NETWORKS' },
  { slot: 'E4', code: 'IT323', name: 'MACHINE LEARNING' },
  { slot: 'E4', code: 'IT425', name: 'NATURAL LANGUAGE PROCESSING' },
  { slot: 'E4', code: 'IT429', name: 'CYBER LAWS' },
  {
    slot: 'E4',
    code: 'MC317',
    name: 'Numerical Methods for Ordinary Diffrential Equations',
  },

  { slot: 'E4', code: 'MC405', name: 'GRAPH THEORY' },
  { slot: 'E4', code: 'ME305', name: 'DESIGN OF MACHINE ELEMENTS' },
  { slot: 'E4', code: 'ME307', name: 'MANUFACTURING TECHNOLOGY -II' },
  { slot: 'E4', code: 'ME361', name: 'INDUSTRIAL ENGINEERING' },
  { slot: 'E4', code: 'ME413', name: 'METROLOGY' },
  { slot: 'E4', code: 'ME415', name: 'PROJECT MANAGEMENT' },
  { slot: 'E4', code: 'ME423', name: 'ADVANCED MANUFACTURING PROCESSES' },
  { slot: 'E4', code: 'PE315', name: 'MECHATRONICS' },
  {
    slot: 'E4',
    code: 'PE411',
    name: 'COMPUTER INTEGRATED DESIGN AND MANUFACTURING',
  },
  { slot: 'E4', code: 'PE419', name: 'PROJECT MANAGEMENT' },
  { slot: 'E4', code: 'SE325', name: 'WEB TECHNOLOGY' },
  { slot: 'E4', code: 'SE427', name: 'Software Project Engineering' },
  { slot: 'E5', code: 'AE307', name: 'COMBUSTION GENERATED POLLUTION' },
  {
    slot: 'E5',
    code: 'AE407',
    name: 'PRODUCTION AND OPERATIONS MANAGEMENT',
  },
  { slot: 'E5', code: 'BT323', name: 'POPULATION GENETICS' },
  { slot: 'E5', code: 'CE315', name: 'ROCK ENGINEERING' },
  {
    slot: 'E5',
    code: 'CE317',
    name: 'SOLID WASTE MANAGEMENT & AIR POLLUTION CONTROL',
  },
  {
    slot: 'E5',
    code: 'CE319',
    name: 'APPLICATION OF GEO-INFORMATICS REMOTE SENSING AND GIS IN ENGINEERING',
  },
  { slot: 'E5', code: 'CH307', name: 'Petroleum Refining Engineering' },
  { slot: 'E5', code: 'CO313', name: 'COMPUTER GRAPHICS' },
  { slot: 'E5', code: 'CO327', name: 'MACHINE LEARNING' },
  { slot: 'E5', code: 'CO429', name: 'Neural Networks' },
  { slot: 'E5', code: 'C0433', name: 'Distributed Systems' },
  { slot: 'E5', code: 'EC315', name: 'Computer Communication Networks' },
  { slot: 'E5', code: 'EC413', name: 'Power Electronics' },
  { slot: 'E5', code: 'EC457', name: 'Natural Language Processing' },
  { slot: 'E5', code: 'EC461', name: 'Multi-rate Signal Processing' },
  {
    slot: 'E5',
    code: 'EE315',
    name: 'DIGITAL CONTROL AND STATE VARIABLE ANALYSIS',
  },
  {
    slot: 'E5',
    code: 'EE327',
    name: 'Introduction to Python Programming',
  },
  {
    slot: 'E5',
    code: 'EE419',
    name: 'PULSE WIDTH MODULATION FOR POWER CONVERTERS',
  },
  { slot: 'E5', code: 'EN309', name: 'Water Resource System' },
  {
    slot: 'E5',
    code: 'EN407',
    name: 'VIBRATION ANALYSIS & CONTROL OF NOISE POLLUTION',
  },
  {
    slot: 'E5',
    code: 'EP351a',
    name: 'PHYSICS OF ENGINEERING MATERIALS',
  },
  { slot: 'E5', code: 'HU403', name: 'Economic Growth' },
  { slot: 'E5', code: 'IT321', name: 'MALWARE ANALYSIS' },
  { slot: 'E5', code: 'IT433', name: 'MULTIMODAL DATA PROCESSING' },
  { slot: 'E5', code: 'MC305', name: 'OPERATION RESEARCH' },
  { slot: 'E5', code: 'MC411', name: 'Data Warehousing & Data Mining' },
  { slot: 'E5', code: 'ME353a', name: 'RENEWABLE SOURCES OF ENERGY' },
  { slot: 'E5', code: 'ME409', name: 'MECHATRONICS & CONTROL' },
  { slot: 'E5', code: 'ME427', name: 'OPERATIONS RESEARCH' },
  { slot: 'E5', code: 'PE361a', name: 'TOTAL QUALITY MANAGEMENT' },
  { slot: 'E5', code: 'SE327', name: 'METHOD IN DATA ANALYTICS' },
  {
    slot: 'E6',
    code: 'CH201',
    name: 'Chemical Engineering Process Calculations',
  },
  { slot: 'E6', code: 'CH203', name: 'Transport Phenomena' },
  { slot: 'E6', code: 'CH301', name: 'Polymeric Materials' },
  { slot: 'E6', code: 'CH303', name: 'Mass Transfer - 1' },
  {
    slot: 'E6',
    code: 'EN301',
    name: 'Water Supply and Environmental Sanitation',
  },

  { slot: 'E6', code: 'ME427', name: 'OPERATIONS RESEARCH' },
  { slot: 'E6', code: 'PE353a', name: 'SUPPLY CHAIN MANAGEMENT' },
  { slot: 'E7', code: 'CE405', name: 'DESIGN OF STEEL STRUCTURES' },
  { slot: 'E7', code: 'CE419', name: 'SOIL DYNAMICS' },
  { slot: 'E7', code: 'CH417', name: 'Polymer Waste Management' },
  { slot: 'E7', code: 'CO415', name: 'WIRELESS AND MOBILE COMPUTING' },
  { slot: 'E7', code: 'CO433', name: 'Distributed Systems' },
  { slot: 'E7', code: 'EE409', name: 'SWITCHGEAR AND PROTECTION' },
  { slot: 'E7', code: 'EN415', name: 'System Simulation & Modeling' },
  { slot: 'E7', code: 'EP427', name: 'Thermodynamics of Materials' },
  {
    slot: 'E7',
    code: 'IT427',
    name: 'INTRUSION DETECTION AND INFORMATION WARFARE',
  },
  { slot: 'E7', code: 'ME427', name: 'OPERATIONS RESEARCH' },
  {
    slot: 'E7',
    code: 'ME433',
    name: 'COMPUTER INTEGRATED MANUFACTURING',
  },
  { slot: 'E7', code: 'PE417', name: 'MATERIALS MANAGEMENT' },
  { slot: 'E8', code: 'AE405', name: 'DESIGN OF AUTOMOBILE COMPONENTS' },
  { slot: 'E8', code: 'CE407', name: 'WATER RESOURCES ENGINEERING' },
  {
    slot: 'E8',
    code: 'CE415',
    name: 'TRANSPORTATION SAFETY AND ENVIRONMENT',
  },
  { slot: 'E8', code: 'CO427', name: 'WEB TECHNOLOGY' },
  {
    slot: 'E8',
    code: 'EE417',
    name: 'ADVANCED TOPICS IN ELECTRICAL MACHINES',
  },
  {
    slot: 'E8',
    code: 'EN411',
    name: 'OCCUPATIONAL HAZARDS, HEALTH & SAFETY',
  },
  { slot: 'E8', code: 'EP423', name: 'SPACE AND ATMOSPHERIC SCIENCE-I' },
  { slot: 'E8', code: 'MC413', name: 'COMPILER DESIGN' },
  { slot: 'E8', code: 'ME427', name: 'OPERATIONS RESEARCH' },
  { slot: 'E8', code: 'SE409', name: 'SOFTWARE MAINTENANCE' },
  { slot: 'E8', code: 'BT413', name: 'NANOBIOTECHNOLOGY' },
  {
    slot: 'E8',
    code: 'CE411',
    name: 'INTERACTION BEHAVIOR OF SOIL STRUCTURES',
  },
  {
    slot: 'E8',
    code: 'CE423',
    name: 'ADVANCED TRANSPORTATION ENGINEERING',
  },
  { slot: 'E8', code: 'CE429', name: 'Disaster Induced Risk' },
  { slot: 'E8', code: 'EE413', name: 'POWER SYSTEM RELIABILITY' },
  { slot: 'E8', code: 'EE415', name: 'DESIGN OF ELECTRICAL MACHINES' },
  { slot: 'E8', code: 'ME407', name: 'REFRIGERATION & AIR CONDITIONING' },
  { slot: 'E8', code: 'ME413', name: 'METROLOGY' },
]

const subjectsBySlot = {
  E1: [...subjects.filter((s) => s.slot === 'E1')],
  E2: [...subjects.filter((s) => s.slot === 'E2')],
  E3: [...subjects.filter((s) => s.slot === 'E3')],
  E4: [...subjects.filter((s) => s.slot === 'E4')],
  E5: [...subjects.filter((s) => s.slot === 'E5')],
  E6: [...subjects.filter((s) => s.slot === 'E6')],
  E7: [...subjects.filter((s) => s.slot === 'E7')],
  E8: [...subjects.filter((s) => s.slot === 'E8')],
}

const subjectsByDept = {
  CO: [...subjects.filter((s) => s.code.startsWith('CO'))],
  IT: [...subjects.filter((s) => s.code.startsWith('IT'))],
  SE: [...subjects.filter((s) => s.code.startsWith('SE'))],
  EE: [...subjects.filter((s) => s.code.startsWith('EE'))],
  EC: [...subjects.filter((s) => s.code.startsWith('EC'))],
  AE: [...subjects.filter((s) => s.code.startsWith('AE'))],
  MC: [...subjects.filter((s) => s.code.startsWith('MC'))],
  ME: [...subjects.filter((s) => s.code.startsWith('ME'))],
  CH: [...subjects.filter((s) => s.code.startsWith('CH'))],
  CE: [...subjects.filter((s) => s.code.startsWith('CE'))],
  HU: [...subjects.filter((s) => s.code.startsWith('HU'))],
  PE: [...subjects.filter((s) => s.code.startsWith('PE'))],
  EN: [...subjects.filter((s) => s.code.startsWith('EN'))],
  EP: [...subjects.filter((s) => s.code.startsWith('EP'))],
  BT: [...subjects.filter((s) => s.code.startsWith('BT'))],
}

export { subjects, subjectsBySlot, subjectsByDept }
